// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTSL_q4LJ6XYucf1ODzguLc63RaaPMgq8',
    appId: '1:188179380448:web:67f9fd29e635bf58d93885',
    messagingSenderId: '188179380448',
    projectId: 'crud-e5a9f',
    authDomain: 'crud-e5a9f.firebaseapp.com',
    storageBucket: 'crud-e5a9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmtA8e06Xd2Nh7HzHYO_YKBY-yfew_vm8',
    appId: '1:188179380448:android:092a047e989fc5a2d93885',
    messagingSenderId: '188179380448',
    projectId: 'crud-e5a9f',
    storageBucket: 'crud-e5a9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7x8dkasXIph3o4XWM5eRFu9wuuzbX4E',
    appId: '1:188179380448:ios:76094e987deeae59d93885',
    messagingSenderId: '188179380448',
    projectId: 'crud-e5a9f',
    storageBucket: 'crud-e5a9f.firebasestorage.app',
    iosBundleId: 'com.example.onlinenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh7x8dkasXIph3o4XWM5eRFu9wuuzbX4E',
    appId: '1:188179380448:ios:76094e987deeae59d93885',
    messagingSenderId: '188179380448',
    projectId: 'crud-e5a9f',
    storageBucket: 'crud-e5a9f.firebasestorage.app',
    iosBundleId: 'com.example.onlinenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTSL_q4LJ6XYucf1ODzguLc63RaaPMgq8',
    appId: '1:188179380448:web:62bbf4314a1d0c94d93885',
    messagingSenderId: '188179380448',
    projectId: 'crud-e5a9f',
    authDomain: 'crud-e5a9f.firebaseapp.com',
    storageBucket: 'crud-e5a9f.firebasestorage.app',
  );
}
